### ISSUE TITLE
Viper plugin seems to be stuck on all files

### ISSUE THREAD

**Issue by alexanderjsummers** [viperproject/viper-ide#296]
I don't seem to be able to run the Viper extension; updating VSCode didn't help (nor did updating the dependencies); the plugin seems to be up-to-date. Strangely, I don't see the usual "Stop" button in the bottom bar any more.

I can't see anything super suspicious in the Viper output, but in the output for the Viper Language Server I see:

Error: Error handling configuration change: Error: GetViperFileEndings request was rejected by the client: Error: Unhandled method GetViperFileEndings
    at c:\Users\alexa\.vscode\extensions\viper-admin.viper-2.4.2\server\index.js:2:770175
    at Generator.throw (<anonymous>)
    at n (c:\Users\alexa\.vscode\extensions\viper-admin.viper-2.4.2\server\index.js:2:768226)
[Error - 15:15:42] Connection to server got closed. Server will not be restarted.

**Comment by ArquintL** [comment]
This is a known issue and should be fixed by an upcoming major revision of the IDE.
The problem seems to be that unzipping the Viper Tools has non-deterministic behavior and sometimes fails - sometimes not. What works is to download a particular Viper Tools release from `Releases` and manually unzip and the expected destination. Viper-IDE will then pick up the tools and simply use them instead of downloading and unzipping them itself

**Comment by alexanderjsummers** [comment]
Thanks a lot! I will try that out

**Comment by ArquintL** [comment]
fixed by #113
