### ISSUE TITLE
Abortion of task not awaited correctly

### ISSUE THREAD

**Issue by jthomme1** [viperproject/viper-ide#370]
Aborting a verification task may abort also following verification requests.

This can become evident running the test `Viper Tools Update Test & test abort of first verification` in `client/src/test/3_updateTools.test`, 

Although awaiting the `aborted` promise in line 52, this causes the subsequently verification that is started in line 58 to also be aborted (see attached [viper.log](https://github.com/viperproject/viper-ide/files/10833850/viper.log) (obtained by running this test in isolation)).

It can be verified that this is the case by comparing it to the attached log ([viper_mod.log](https://github.com/viperproject/viper-ide/files/10833851/viper_mod.log)), which was obtained by applying the following diff before running the test:
```
diff --git a/client/src/test/3_updateTools.test.ts b/client/src/test/3_updateTools.test.ts
index d0393c5..80d87d0 100644
--- a/client/src/test/3_updateTools.test.ts
+++ b/client/src/test/3_updateTools.test.ts
@@ -52,6 +52,7 @@ suite('Viper Tools Update Test', () => {
         await aborted;
         TestHelper.log("verification has been aborted");
         await TestHelper.checkForRunningProcesses(false, false, true);
+        await new Promise(resolve => setTimeout(resolve, 500));
 
         //reverify
         await TestHelper.openAndVerify(LONG);
```

This suggests that maybe the abortion task might still be in the list of tasks that are worked on by the VerificationController although the Promise returned.

@ArquintL (was told to tag you)

**Comment by ArquintL** [comment]
Thanks for reporting this issue.
I've had a look at it seems that the problem is rather in ViperServer, i.e. it keeps sending messages from the backends despite abortion. I believe this then results in viper-ide misinterpreting these messages as belonging already to the next verification.
I've prepared a [fix in ViperServer](https://github.com/viperproject/viperserver/tree/proper-abort). You can find a JAR based on that branch [here](https://polybox.ethz.ch/index.php/s/54sDcqHDJHelKBY). Could you please quickly check whether this indeed resolves the issue also at your end?
Thanks!

**Comment by jthomme1** [comment]
I just tested it (although on a different machine) and the tests all pass!
Thanks for taking the time and fixing this!
